const obj = {
  Kitab: {
    "Bədii ədəbiyyat": [
      "Antologiya",
      "Bioqrafiya, avtobioqrafiya & Xatirə",
      "Detektiv",
      "Elmi-fantastika & Fantaziya",
      "Fəlsəfə",
      "Hekayələr & Oçerklər",
      "Kino və teatr",
      "Klassik poemalar",
      "Klassiklər",
      "Komiks",
      "Macəra",
      "Mifologiya",
      "Nağıllar",
      "Poemalar",
      "Psixologiya",
      "Romanlar & Novellalar",
      "Satira",
      "Tarix, hüquq & Siyasi",
      "Tarixi roman",
      "Triller, mistika & Qorxu",
      "Təhsil, mənbə & Dil",
    ],
    "Qeyri-bədii ədəbiyyat": [
      "Ailə",
      "Akademik",
      "Aşpazlıq",
      "Astronomiya",
      "Bağbanlıq",
      "Bioqrafiya, avtobioqrafiya & Xatirə",
      "Biznes & İqtisadiyyat",
      "Detektiv",
      "Dini",
      "Dəb",
      "Elm",
      "Ensiklopediyalar & Atlaslar",
      "Ezoterika",
      "Fəaliyyətlər",
      "Fəlsəfə",
      "Hekayələr & Esselər",
      "Heyvanlar",
      "Jurnallar & Qəzetlər",
      "Kino və teatr",
      "Klassiklər",
      "Komiks",
      "Kompüter elmləri",
      "Mifologiya",
      "Musiqi",
      "Poemalar",
      "Psixologiya",
      "Publisistika",
      "Qeyri-bədii",
      "Regional maraqlar",
      "Romanlar & Novellalar",
      "Sağlamlıq, tibbi & İdman",
      "Sitatlar & Aforizmlər",
      "Sosiologiya",
      "Sənət, arxitektura, dizayn & Fotoqrafiya",
      "Şəxsi inkişaf",
      "Səyahət & Məkanlar",
      "Tarix, hüquq & Siyasi",
      "Tarixi roman",
      "Təhsil, mənbə & Dil",
      "Xəritələr",
    ],
    "Bədii uşaq ədəbiyyatı": [
      "3D Kitab",
      "Detektiv",
      "Elmi-fantastika & Fantaziya",
      "Hekayələr & Oçerklər",
      "Heyvanlar",
      "Klassik poemalar",
      "Klassiklər",
      "Komiks",
      "Macəra",
      "Nağıllar",
      "Oyuncaq kitablar",
      "Poemalar",
      "Romanlar & Novellalar",
      "Satira",
      "Səsli kitab",
      "Tarixi roman",
      "Triller, mistika & Qorxu",
      "Təhsil, mənbə & Dil",
    ],
    "Qeyri-bədii uşaq ədəbiyyatı": [
      "3D Kitab",
      "Ailə",
      "Aşpazlıq",
      "Astronomiya",
      "Bioqrafiya, avtobioqrafiya & Xatirə",
      "Biznes & İqtisadiyyat",
      "Dini",
      "Dəb",
      "Elm",
      "Ensiklopediyalar & Atlaslar",
      "Fəaliyyətlər",
      "Fəlsəfə",
      "Heyvanlar",
      "Jurnallar & Qəzetlər",
      "Kino və teatr",
      "Klassiklər",
      "Komiks",
      "Kompüter elmləri",
      "Mifologiya",
      "Musiqi",
      "Nağıllar",
      "Oyuncaq kitablar",
      "Psixologiya",
      "Qeyri-bədii",
      "Sağlamlıq, tibbi & İdman",
      "Sitatlar & Aforizmlər",
      "Sənət, arxitektura, dizayn & Fotoqrafiya",
      "Səsli kitab",
      "Şəxsi inkişaf",
      "Səyahət & Məkanlar",
      "Tarix, hüquq & Siyasi",
      "Təhsil, mənbə & Dil",
      "Xəritələr",
    ],
  },
  "Elektronika & aksessuar": {
    "Çanta & Çamadanlar": [
      "Bel çantası",
      "Biznes çantası",
      "Çiyin çantası",
      "Çoxfunksiyalı çanta",
      "Etiket",
      "Fotoaparat çantası",
      "İstirahət & İdman Çantaları",
      "Noutbuk üzlük & çantaları",
      "Plastik çamadanlar",
      "Pulqabı",
      "Şəxsi gigiyena çantası",
      "Təkərli çamadan",
    ],
    Multimedia: ["CD"],
    "Rəqəmsal cihazlar": [
      "Ağıllı saat & Fitnes bələdçi",
      "Kamera & Media qurğu alətləri",
      "Masaüstü lampa",
    ],
    "Səyahət aksesuarları": [
      "Boyun yastığı",
      "Çamadan qıfılı",
      "Çətir",
      "Maska",
      "Su qabı & Saxlancları",
      "Səyahət corabları",
      "Səyahət dəsti",
      "Xətkeş",
    ],
    "Telefon & Kompüter aksesuarları": [
      "Adapterlər & Çeviricilər",
      "Enerji saxlayıcılar & Batareyalar",
      "Enerji toplama cihazı & Kabellər",
      "Fleş disk & Yaddaş kartı",
      "Klaviatura & Coystiklər",
      "Monopodlar & Tripodlar",
      "Qulaqlıq & Akustika",
      "Smartfon üzlükləri",
      "Tutucular & Çexol",
    ],
  },
  "Oyuncaqlar & Oyunlar": {
    "İdman & Açıq hava oyunları": [
      "Atıcılar & Köpük oyunu",
      "Hədəf",
      "Skuter & Aksesuarları",
      "Tenis & Badminton",
    ],
    "Öyrədici oyun & Oyuncaqlar": [
      "3D Model",
      "Avtomobillər",
      "İlk oyuncaqlar",
      "İnşaat oyuncaqları",
      "Kaleydoskoplar",
      "Kinetik qum",
      "Mikroskop & Teleskop",
      "Musiqili oyuncaqlar",
      "Oyunlar & Fəaliyyətlər",
      "Rubik kubu",
      "Slaym & Yumşaq növ",
    ],
    "Oyuncaq modelləri & Aksesuarları": [
      "Doldurulmuş oyuncaqlar",
      "Hərəkətli oyuncaqlar",
      "Maşınlar",
      "Yumşaq oyuncaqlar",
    ],
    Puzllar: ["Puzzle & Aksesuarlar"],
    "Zəka & Ənənəvi oyunlar": [
      "Masaüstü oyunlar",
      "Məktəbəqədər oyunlar",
      "Oyun kartları",
      "Zəka oyunları",
    ],
  },
  Dəftərxana: {
    "Kağız ləvazimatları": [
      "Açıqçalar",
      "Eskiz dəftəri",
      "Gündəlik & Jurnal",
      "Kağız ləvazimatları",
      "Qeyd dəftəri",
      "Qeyd kağızı",
      "Rəsmçəkmə altlıqları",
      "Təqvim",
      "Zərflər",
    ],
    "Məktəb & Ofis": [
      "Dəlgec",
      "Fosforlu qələmlər",
      "Halqa rezinlər",
      "Hesablayıcı",
      "Kağız tutucu",
      "Karandaş qabları",
      "Karandaş yonan",
      "Kompas",
      "Lövhə",
      "Lupa",
      "Masa dəsti & Aksesuar tutucu",
      "Məktəb çantası",
      "Pozan",
      "Qayçı",
      "Qida çantası",
      "Qlobus",
      "Sancaq",
      "Stepler & Ehtiyatları",
      "Sənəd qovluğu & Tutacaq",
      "Tullantı səbətləri",
      "Təmizlik vasitələri",
      "Universal bıçaq & Ehtiyatları",
      "Xətkeş",
      "Yapışdırıcı",
      "Yapışqan lent qurğusu & Kəsici",
      "Yapışqan lentlər",
    ],
    Uniforma: [
      "Gödəkcə",
      "İdman forması",
      "Köynək",
      "Qalstuk",
      "Qısaqol köynək",
      "Şalvar",
      "Sviter",
      "Ətək",
    ],
    "Yazı & Rəsm": [
      "Boyalar & Boya aksesuarları",
      "Flomasterlər",
      "Karandaş & Karandaş dəstləri",
      "Kətan rəsm & Aksessuarları",
      "Pastel qələm",
      "Qələm & Qələm dəstləri",
    ],
  },
  "Hədiyyələr & Hobbi": {
    "Hədiyyə Kartları": [],
    "İncəsənət & Sənətkarlıq": ["3D qələm & 3D ip", "Boyama & Kreativlik"],
    Pazllar: ["Pazl & Aksesuarlar"],
    "Suvenir & Dekorasiya": [
      "Açarlıq",
      "Bayraq",
      "Dekorasiya",
      "Foto albom & Çərçivələr",
      "Foto yapışqan",
      "Maqnit",
      "Milli suvenirlər",
      "Musiqili qutu",
      "Pinlər",
      "Qablaşdırma kağızları & Qutuları",
      "Qəpiklik",
      "Yeni il bəzəkləri",
      "Əlfəcin & Yapışqanlar",
    ],
  },
};

export default obj;
